micronaut:
  application:
    name: product-service

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

